# Blueprint for Kfoodle application with PostgreSQL database, SFTP, backend, and frontend services.
services:
  - type: web
    plan: free
    name: kfoodle-backend
    runtime: docker
    dockerfilePath: ./backend/Kfoodle/Dockerfile
    buildCommand: "docker build -t kfoodle-backend ./backend/Kfoodle/"
    startCommand: "docker run -p 5201:8080 --env JWT__ValidAudience=Blablacar --env JWT__ValidIssuer=Blablacar --env JWT__Secret='this is my custom Secret key for authentication' --env EmailSettings__FromName='Антон Борисов' --env EmailSettings__EmailAddress=borisov.as2015@yandex.ru --env EmailSettings__Password='arigudeqaaztkkfn' --env EmailSettings__SMTPServerHost=smtp.yandex.ru --env EmailSettings__SMTPServerPort=465 --env Authentication__VK__AppId=51903164 --env Authentication__VK__AppSecret=t1cFz2DZLq8KsxhpYPz0 --env Authentication__VK__ServiceToken=991675219916752199167521ca9a018f9d9991699167521ff0a8c49759c08682aca5eae --env Authentication__VK__VkGetInfoUserUri=https://api.vk.com/method/auth.getProfileInfoBySilentToken --env Authentication__VK__VkApiVersion=5.199 --env Authentication__Yandex__AppId=51e4d0a49d994b6280c3fca62af75566 --env Authentication__Yandex__AppSecret=7ea83902a7ee421381f0b4e6be4d7e9c --env Sftp__Host=kfoodle-sftp --env Sftp__Port=22 --env Sftp__User=demo --env Sftp__Password=demo --env SearchCity__Host=https://kladr-api.ru/api.php --env SearchCity__Token=kaeYEGATH2fbe7Q67YR6aQRySyZznBz5 --env ConnectionStrings__DefaultConnection='Host=kfoodle-db;Username=postgres;Password=postgres;Database=kfoodle_database' kfoodle-backend"

  - type: web
    plan: free
    name: kfoodle-frontend
    runtime: docker
    dockerfilePath: ./frontend/kfoodle/Dockerfile
    buildCommand: "docker build -t kfoodle-frontend ./frontend/kfoodle"
    startCommand: "docker run -p 8080:80 --env VITE_API_URL=http://kfoodle-backend:8080 kfoodle-frontend"

databases:
  - name: kfoodle-db
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
      - key: POSTGRES_DB
        value: kfoodle_database

  - name: kfoodle-sftp
    type: web
    plan: free
    image: emberstack/sftp
    envVars:
      - key: USERS
        value: demo:demo:1001:1001

volumes:
  - name: db_data
  - name: sftp_data
