name: CI

on: [push]

env:
  backend-dotnet-path: './backend/Kfoodle/'
  frontend-path: './frontend/kfoodle/'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ['backend-dotnet', 'frontend']
        dotnet-version: [8.0.x]
        node-version: [20.x]
    
    steps:
    # Backend
    - uses: actions/checkout@v4
    - name: Setup .NET
      if: matrix.project == 'backend-dotnet'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore .NET dependencies
      if: matrix.project == 'backend-dotnet'
      run: dotnet restore ${{ env.backend-dotnet-path }}/Kfoodle.sln
    - name: Build .NET app
      if: matrix.project == 'backend-dotnet'
      run: dotnet build ${{ env.backend-dotnet-path }}/Kfoodle.sln --no-restore

    # Frontend
    - name: Use Node.js
      if: matrix.project == 'frontend'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies from package.json
      if: matrix.project == 'frontend'
      run: npm ci --prefix ${{ env.frontend-path }}
    - name: Build React.js app
      if: matrix.project == 'frontend'
      run: npm run build --prefix ${{ env.frontend-path }}
    # run: npm test
    #- name: Test
    # run: dotnet test ${{env.backend-dotnet-path}}/Kfoodle.sln --no-build --verbosity normal
