# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: [push]

env:
  backend-dotnet-path: './backend/Kfoodle/'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.backend-dotnet-path}}/Kfoodle.sln
    - name: Build
      run: dotnet build ${{env.backend-dotnet-path}}/Kfoodle.sln --no-restore
    - name: Test
      run: dotnet test ${{env.backend-dotnet-path}}/Kfoodle.sln --no-build --verbosity normal
